# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OutlookBusySync < Formula
  desc "Mirror busy blocks between two Microsoft 365 calendars"
  homepage "https://github.com/michalkechner-impact/outlook-busy-sync"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/michalkechner-impact/outlook-busy-sync/releases/download/v0.3.1/outlook-busy-sync_0.3.1_darwin_amd64.tar.gz"
      sha256 "43f653b87913a514bc42289a6288358746c37877c22f6e83df9e08452949d2d1"

      define_method(:install) do
        bin.install "outlook-busy-sync"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/michalkechner-impact/outlook-busy-sync/releases/download/v0.3.1/outlook-busy-sync_0.3.1_darwin_arm64.tar.gz"
      sha256 "b40b9447ac5cf48f4f670d61696108371021153b7637cb5d2442a720fdd6c4bb"

      define_method(:install) do
        bin.install "outlook-busy-sync"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/michalkechner-impact/outlook-busy-sync/releases/download/v0.3.1/outlook-busy-sync_0.3.1_linux_amd64.tar.gz"
      sha256 "f59a1ffc0ca4a7c4bbe410bd37198fb7aeb716753c94611c305125b7fc4ce9e5"
      define_method(:install) do
        bin.install "outlook-busy-sync"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/michalkechner-impact/outlook-busy-sync/releases/download/v0.3.1/outlook-busy-sync_0.3.1_linux_arm64.tar.gz"
      sha256 "9d60ecb2b64f665d38e5163d7893895ffb3abfe3233a99ec3bb3933a077a35f0"
      define_method(:install) do
        bin.install "outlook-busy-sync"
      end
    end
  end

  test do
    system "#{bin}/outlook-busy-sync", "--version"
  end
end
