# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OutlookBusySync < Formula
  desc "Mirror busy blocks between two Microsoft 365 calendars"
  homepage "https://github.com/michalkechner-impact/outlook-busy-sync"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/michalkechner-impact/outlook-busy-sync/releases/download/v0.2.1/outlook-busy-sync_0.2.1_darwin_amd64.tar.gz"
      sha256 "1bf168469074286c78e469b71559d0a79374e0684ff1f615336bdbff765b49a7"

      define_method(:install) do
        bin.install "outlook-busy-sync"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/michalkechner-impact/outlook-busy-sync/releases/download/v0.2.1/outlook-busy-sync_0.2.1_darwin_arm64.tar.gz"
      sha256 "d3010b50597bc86f226ceb2372ec1668408f84247a3efc21db69452e72f888f2"

      define_method(:install) do
        bin.install "outlook-busy-sync"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/michalkechner-impact/outlook-busy-sync/releases/download/v0.2.1/outlook-busy-sync_0.2.1_linux_amd64.tar.gz"
      sha256 "33d4bc95b2948af6237519e4838035260a96605768e7c0599e49cee071c9a488"
      define_method(:install) do
        bin.install "outlook-busy-sync"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/michalkechner-impact/outlook-busy-sync/releases/download/v0.2.1/outlook-busy-sync_0.2.1_linux_arm64.tar.gz"
      sha256 "639917089a078bee07e54deb7bc3a727bc8fa18bd0e9febba6e40b7367ed1743"
      define_method(:install) do
        bin.install "outlook-busy-sync"
      end
    end
  end

  test do
    system "#{bin}/outlook-busy-sync", "--version"
  end
end
